### PR TITLE
Rake tasks to start and stop EC2 instances

### PR DESCRIPTION
**Pull request by wbushey**
Also Cleaning up import tree task

This is the first step in a plan I have to automate most of the pull request process. Currently, when Adopt-A-Tree gets a pull request, I do the following manually:
 - Review the pull request's changes
 - Start the stage environment (an EC2 instance we keep off to cut down on costs)
 - Deploy the pull request to stage
 - Go through the tree adoption & unadoption process
 - Stop the stage environment
 - Accept the pull request
 - Deploy master to production

With the exception of reviewing and accepting a pull request, all of this can be automated.

### CODE REVIEW

**Comment by wbushey** [comment]
@jhsu802701, this is the first time I've noticed CircleCI running, which is great. I've been considering switching from Travis to CircleCI. But, I do not see a CircleCI config in the repo. How does CircleCI know what to run?

**Comment by jhsu802701** [comment]
CircleCI 2.0 requires a config file but 1.0 does not.

However, I'm in the process of switching from CircleCI to Travis.  Travis has a much simpler config file.

**Comment by wbushey** [comment]
@jhsu802701 , do you know of any good examples of creating deployment pipelines with Travis? While Travis does have a simpler configuration, I've found that it is also more limited in what it can be used for. I'd really like to be able to automate as much of the testing and deployment process as possible.

**Comment by jhsu802701** [comment]
I've never used Travis for deployment - only for continuous integration testing.

**Pull request merged**
