### PR TITLE
Adding description of the password requirements

### LINKED ISSUE #9: Tell users about password requirements
Currently, the site does not tell a user what the requirements are for a user password (which I beleive are at least 8 characters, with at least one number and one letter). The user is also not given an error message if they submit a password that does not meet the criteria.

### PR DESCRIPTION
**Pull request by wbushey**
Fixes #9

### CODE REVIEW

**Comment by wbushey** [comment]
@jhsu802701, would you be willing to take a look at this pull request, and comment on whether it's good to go, or if you see any issues?

**Comment by jhsu802701** [comment]
Travis is showing a test failure: 

 1) Adoption Form Not signed in user clicks a thing Displays the "Sign in to adopt" message

     Failure/Error: visit root_path

     

     Capybara::Poltergeist::StatusFailError:

       Request to 'http://127.0.0.1:33619/' failed to reach server, check DNS and/or server status

**Comment by wbushey** [comment]
Rebased after merging #78 yesterday. Tests are now passing, after rerunning them several times.

**Comment by wbushey** [comment]
This has been deployed to stage and production.

**Pull request merged**
